### ISSUE TITLE
Problems/improvements in the setup of the inaetics demonstrator.

### ISSUE THREAD

**Issue by ErjanAltena** [INAETICS/demonstrator#4]
I used the installation and setup guide for the demonstrator (downloaded from inaetics.org). I 
found some issues in the SW and improvements for the document:

The machine I used was a Core-I5 machine with 6GB RAM. This is no enough since 6 VM's are started with each 1GB of memory. I scaled the images down to 512MB but startup gave some problems. Manual restarting  some docker images solved this and the system was up and running.

I think it should be mentioned that the minimal memory requirement is 16 GB.

On CentOS 6 the installation instructions for vagrant and virtualbox  with yum don't work. I downloaded the RPM's from the internet and installed them manualy. 

The instruction
  vboxmanage hostonlyif remove vboxnet0
does not work after a fresh install. It works after a vagrant up/halt cycle. (If  VirtualBox has run once then the vboxnet0 interface is known)

Both the bootstrap as the workers do not start. They fail on a NFS mount in the Vragantfile I changed the NFS mode to rsyn:
    config.vm.synced_folder "docker-registry-service", "/var/lib/docker-registry-service", type:"rsync"
    config.vm.synced_folder "../docker-images", "/home/core/docker-images", type:"rsync"
and for the workers Vragantfile:
    config.vm.synced_folder "inaetics/", "/opt/inaetics", type:"rsync"

On the 5th page of the manual, the 1st and second line form one command. This could be made more explicit. Also starting the provisioning server as the celix server takes quite a while (both about 5 minutes). Mentioning this prevents aborting the installation.

On page 6 the instruction to sh to worker-1 is not needed. If you follow the instruction you are already logged-in.

**Comment by pnoltes** [comment]
Thanks for trying out the demonstrator. We will look into this issue and when needed update the documentation.

**Comment by jawi** [comment]
I've updated the Vagrantfiles and user guide to reflect your changes and suggestions. @ErjanAltena: can you take a look at this to see if this resolves your issues?
